DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS trade;
DROP TABLE IF EXISTS deposit;
DROP TABLE IF EXISTS account;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE account (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    balance FLOAT NOT NULL,
    user INTEGER NOT NULL,
    FOREIGN KEY (user) REFERENCES user (id)
);

CREATE TABLE deposit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    value FLOAT NOT NULL,
    FOREIGN KEY (user) REFERENCES user (id)
);

CREATE TABLE trade (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    price FLOAT NOT NULL,
    qty INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    -- dir = -1 => BUY 
    -- dir = 1 => SELL
    dir INTEGER NOT NULL,
    FOREIGN KEY (user) REFERENCES user (id)
);